parameters:
  vmImage: ''
  message: ''

stages:
- stage: BuildWithStagesTemplate
  displayName: 'Build with Stages Template'

  jobs:
  - job: TemplatedStage
    displayName: 'Templated Stage'

    pool:
      vmImage: '${{ parameters.vmImage }}'

    workspace:
      clean: all

    steps:
    - task: PowerShell@2
      displayName: 'Echo Greeting in PowerShell'
      inputs:
        targetType: Inline
        script: |
          Write-Host "$(Greeting)"
          Write-Host "${{ parameters.message }}"
