parameters:
  message: ''

steps:
- task: PowerShell@2
  displayName: 'Echo Greeting in PowerShell'
  inputs:
    targetType: Inline
    script: |
      Write-Host "$(Greeting)"
      Write-Host "${{ parameters.message }}"
